package com.discordrive.gallery.crypto

import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import kotlinx.serialization.json.int
import org.junit.jupiter.api.Assertions.assertArrayEquals
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Test

/**
 * Verifies byte-exact compatibility with @ddv4/processing using the shared
 * crypto-vectors.json (generated by discordrive's
 * scripts/generate-crypto-vectors.mts). If any of these fail, the Kotlin
 * client would corrupt or fail to read data produced by the web client.
 */
class CryptoVectorsTest {

    private val vectors: JsonObject = Json.parseToJsonElement(
        requireNotNull(javaClass.getResourceAsStream("/crypto-vectors.json")) {
            "crypto-vectors.json missing from test resources"
        }.bufferedReader().readText(),
    ).jsonObject

    private fun b64(value: String): ByteArray = DdvCrypto.b64decode(value)

    @Test
    fun `argon2id matches hash-wasm`() {
        for (case in vectors.getValue("argon2id").jsonArray) {
            val obj = case.jsonObject
            val params = Argon2Params(
                memoryKB = obj.getValue("memoryKB").jsonPrimitive.int,
                iterations = obj.getValue("iterations").jsonPrimitive.int,
                parallelism = obj.getValue("parallelism").jsonPrimitive.int,
                saltB64 = obj.getValue("saltB64").jsonPrimitive.content,
            )
            val hash = Argon2.hash(
                password = obj.getValue("password").jsonPrimitive.content,
                salt = b64(params.saltB64),
                params = params,
                hashLength = obj.getValue("hashLength").jsonPrimitive.int,
            )
            assertArrayEquals(
                b64(obj.getValue("hashB64").jsonPrimitive.content),
                hash,
                "argon2id vector '${obj.getValue("name").jsonPrimitive.content}'",
            )
        }
    }

    @Test
    fun `server auth proof derivation matches`() {
        val obj = vectors.getValue("serverAuthProof").jsonObject
        val proof = Hkdf.deriveBits(b64(obj.getValue("argon2HashB64").jsonPrimitive.content), DdvCrypto.INFO_SERVER_AUTH)
        assertArrayEquals(b64(obj.getValue("proofB64").jsonPrimitive.content), proof)
    }

    @Test
    fun `hkdf derivations match WebCrypto`() {
        for (case in vectors.getValue("hkdf").jsonArray) {
            val obj = case.jsonObject
            val okm = Hkdf.deriveBits(
                b64(obj.getValue("ikmB64").jsonPrimitive.content),
                obj.getValue("info").jsonPrimitive.content,
            )
            assertArrayEquals(
                b64(obj.getValue("okmB64").jsonPrimitive.content),
                okm,
                "hkdf info '${obj.getValue("info").jsonPrimitive.content}'",
            )
        }
    }

    @Test
    fun `share capability token matches`() {
        val obj = vectors.getValue("shareCapabilityToken").jsonObject
        val token = DdvCrypto.deriveShareCapabilityToken(b64(obj.getValue("linkSecretB64").jsonPrimitive.content))
        assertArrayEquals(b64(obj.getValue("tokenB64").jsonPrimitive.content), token)
    }

    @Test
    fun `aes-gcm chunk packing matches WebCrypto`() {
        val obj = vectors.getValue("aesGcmChunk").jsonObject
        val packed = AesGcm.encryptPacked(
            key = b64(obj.getValue("keyB64").jsonPrimitive.content),
            plaintext = b64(obj.getValue("plaintextB64").jsonPrimitive.content),
            iv = b64(obj.getValue("ivB64").jsonPrimitive.content),
        )
        assertArrayEquals(b64(obj.getValue("packedB64").jsonPrimitive.content), packed)

        // and the reverse direction
        val decrypted = AesGcm.decryptPacked(
            key = b64(obj.getValue("keyB64").jsonPrimitive.content),
            packed = b64(obj.getValue("packedB64").jsonPrimitive.content),
        )
        assertArrayEquals(b64(obj.getValue("plaintextB64").jsonPrimitive.content), decrypted)
    }

    @Test
    fun `wrapKey packing matches`() {
        val obj = vectors.getValue("wrapKey").jsonObject
        val packed = DdvCrypto.wrapKeyPacked(
            rawKeyToWrap = b64(obj.getValue("keyToWrapB64").jsonPrimitive.content),
            wrappingKey = b64(obj.getValue("wrappingKeyB64").jsonPrimitive.content),
            iv = b64(obj.getValue("ivB64").jsonPrimitive.content),
        )
        assertArrayEquals(b64(obj.getValue("packedB64").jsonPrimitive.content), packed)

        val unwrapped = DdvCrypto.unwrapKeyPacked(packed, b64(obj.getValue("wrappingKeyB64").jsonPrimitive.content))
        assertArrayEquals(b64(obj.getValue("keyToWrapB64").jsonPrimitive.content), unwrapped)
    }

    @Test
    fun `file metadata encryption matches`() {
        val obj = vectors.getValue("fileMetadata").jsonObject
        val rootFek = b64(obj.getValue("rootFekB64").jsonPrimitive.content)
        val packed = DdvCrypto.encryptFileMetadata(
            json = obj.getValue("plaintextJson").jsonPrimitive.content,
            rootFek = rootFek,
            iv = b64(obj.getValue("ivB64").jsonPrimitive.content),
        )
        assertArrayEquals(b64(obj.getValue("packedB64").jsonPrimitive.content), packed)
        assertEquals(
            obj.getValue("plaintextJson").jsonPrimitive.content,
            DdvCrypto.decryptFileMetadata(packed, rootFek),
        )
    }

    @Test
    fun `file manifest encryption matches`() {
        val obj = vectors.getValue("fileManifest").jsonObject
        val rootFek = b64(obj.getValue("rootFekB64").jsonPrimitive.content)
        val packed = DdvCrypto.encryptFileManifest(
            json = obj.getValue("plaintextJson").jsonPrimitive.content,
            rootFek = rootFek,
            iv = b64(obj.getValue("ivB64").jsonPrimitive.content),
        )
        assertArrayEquals(b64(obj.getValue("packedB64").jsonPrimitive.content), packed)
    }

    @Test
    fun `full login material chain`() {
        val argon = vectors.getValue("argon2id").jsonArray[0].jsonObject
        val proof = vectors.getValue("serverAuthProof").jsonObject
        val params = Argon2Params(
            memoryKB = argon.getValue("memoryKB").jsonPrimitive.int,
            iterations = argon.getValue("iterations").jsonPrimitive.int,
            parallelism = argon.getValue("parallelism").jsonPrimitive.int,
            saltB64 = argon.getValue("saltB64").jsonPrimitive.content,
        )
        val material = DdvCrypto.deriveLoginMaterial(argon.getValue("password").jsonPrimitive.content, params)
        assertArrayEquals(b64(argon.getValue("hashB64").jsonPrimitive.content), material.arkWrapKey)
        assertArrayEquals(b64(proof.getValue("proofB64").jsonPrimitive.content), material.serverAuthProof)
    }

    @Test
    fun `round-trip with random keys`() {
        val ark = AesGcm.randomKey()
        val rootFek = AesGcm.randomKey()
        val arkWrapKey = AesGcm.randomKey()

        val wrappedArk = DdvCrypto.wrapKeyPacked(ark, arkWrapKey)
        assertArrayEquals(ark, DdvCrypto.unwrapArkWithPassword(DdvCrypto.b64encode(wrappedArk), arkWrapKey))

        val wrappedFek = DdvCrypto.wrapKeyPacked(rootFek, ark)
        assertArrayEquals(rootFek, DdvCrypto.unwrapRootFek(DdvCrypto.b64encode(wrappedFek), ark))

        val chunk = "round trip chunk".toByteArray()
        assertArrayEquals(chunk, DdvCrypto.decryptChunk(DdvCrypto.encryptChunk(chunk, rootFek), rootFek))
    }
}
